import os

API_KEY = os.environ['CHECKEPISODE_TVDB_API_KEY']
MIRROR = "http://www.thetvdb.com/"
REMOVE_OLD = False
PRINT_DETAIL = True
REMOVE_OLD_IMAGES = False
IMAGE_FOLDER = os.environ['CHECKEPISODE_TVDB_IMAGE_FOLDER']
LAST_UPDATE = os.environ['CHECKEPISODE_TVDB_LASTUPDATE']
SERIES_ZIP = os.environ['CHECKEPISODE_TVDB_SERIES_ZIP']
